sonar.projectKey=luciaLebrun_marginalia
sonar.organization=llebrun
sonar.projectName=Marginalia

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.config.*,src/db/migrations/**,**/*.d.ts,src/app/**/layout.tsx,public/**
sonar.coverage.exclusions=**/*.config.*,src/app/**,src/components/**,src/db/migrations/**,**/fixtures/**
